---
- name: Provision Docker + Nginx on EC2
  hosts: web
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Create custom HTML folder
      file:
        path: /opt/custom-nginx/html
        state: directory
        recurse: yes

    - name: Copy custom HTML file
      copy:
        src: files/index.html
        dest: /opt/custom-nginx/html/index.html

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /opt/custom-nginx/html:/usr/share/nginx/html:ro
